// Generated by CoffeeScript 1.10.0
var OrballBoot;

OrballBoot = function() {
  return {
    music: null,
    orientated: false,
    init: function() {
      this.input.maxPointers = 1;
      this.stage.disableVisibilityChange = true;
      this.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;
      this.scale.pageAlignHorizontally = true;
      this.scale.pageAlignVertically = true;
      this.scale.setResizeCallback(this.gameResized, this);
    },
    preload: function() {
      this.stage.backgroundColor = '#7799AA';
      this.load.image('PreloadBar', 'assets/preloader.gif');
    },
    create: function() {
      this.state.start('Preload');
    },
    gameResized: function(width, height) {},
    enterIncorrectOrientation: function() {
      BasicGame.orientated = false;
      document.getElementById('orientation'.style.display = 'block');
    },
    leaveIncorrectOrientation: function() {
      BasicGame.orientated = true;
      document.getElementById('orientation'.style.display = 'none');
    }
  };
};
