// Generated by CoffeeScript 1.10.0
var OrballMenu;

OrballMenu = function() {
  return {
    create: function() {
      this.logo = this.add.sprite(this.world.centerX, 200, 'ball');
      this.logo.anchor.setTo(0.5, 0.5);
      this.startButton = this.add.button(this.world.centerX, this.world.centerY, 'button-start', this.startGame, this, 2, 0, 1);
      this.startButton.anchor.set(0.5, 0.5);
      this.startButton.input.useHandCursor = true;
    },
    startGame: function(pointer) {
      this.state.start('Game');
    }
  };
};
