// Generated by CoffeeScript 1.10.0
var OrballPreload;

OrballPreload = function() {
  return {
    preload: function() {
      this.preloadBar = this.game.add.sprite(this.world.centerX, this.world.centerY, 'PreloadBar');
      this.load.setPreloadSprite(this.preloadBar, 0.5, 0.5);
      this.load.image('ball', 'assets/ball.png');
      this.load.image('bg', 'assets/bg.png');
      this.load.image('ground', 'assets/platform.png');
      this.load.image('floor', 'assets/floor.png');
      this.load.image('star', 'assets/star.png');
      this.load.image('hole', 'assets/hole.png');
      this.load.image('diamond', 'assets/diamond.png');
      this.load.image('yellowBlock', 'assets/yellow-block.png');
      this.load.image('coin', 'assets/goldCoin.png');
      this.load.spritesheet('dude', 'assets/dude.png', 32, 48);
      this.load.spritesheet('button-start', 'assets/button-start.png', 146, 51);
    },
    create: function() {
      this.state.start('Menu');
    }
  };
};
